# Generated by Django 5.2.1 on 2025-06-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-date'], 'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
        migrations.AddField(
            model_name='investor',
            name='total_invested',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
